ChronosSuite/Controllers/EmployeeController.cs
using ChronosSuite.Models;
using ChronosSuite.Models.Dto.Employee;
using DannteV2.Models.Dto.FiltersTable;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace ChronosSuite.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly PgDbContext _context;

        public EmployeeController(PgDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Employee = "active";
            return View();
        }

        [HttpPost]
        public IActionResult GetAll([FromBody] TableRequest<FilterEmployee>? request)
        {
            try
            {
                if (request == null || request.filter == null)
                    return Json(new { success = false, message = "Solicitud inválida." });

                var query = _context.Employees
                                    .Include(e => e.Company)
                                    .AsQueryable();

                // Aplicar filtros si están presentes
                if (!string.IsNullOrEmpty(request.filter.Id))
                {
                    if (long.TryParse(request.filter.Id, out long employeeId))
                    {
                        query = query.Where(e => e.Id == employeeId);
                    }
                }

                if (!string.IsNullOrEmpty(request.filter.FirstName))
                    query = query.Where(e => e.FirstName.Contains(request.filter.FirstName));

                if (!string.IsNullOrEmpty(request.filter.LastName))
                    query = query.Where(e => e.LastName.Contains(request.filter.LastName));

                if (!string.IsNullOrEmpty(request.filter.Position))
                    query = query.Where(e => e.Position.Contains(request.filter.Position));

                if (!string.IsNullOrEmpty(request.filter.Email))
                    query = query.Where(e => e.Email.Contains(request.filter.Email));

                if (!string.IsNullOrEmpty(request.filter.PhoneNumber))
                    query = query.Where(e => e.PhoneNumber.Contains(request.filter.PhoneNumber));

                if (!string.IsNullOrEmpty(request.filter.Company))
                {
                    query = query.Where(e => e.Company != null && e.Company.Name.Contains(request.filter.Company));
                }

                // Aplicar ordenamiento
                if (!string.IsNullOrEmpty(request.sort))
                {
                    query = request.order == "desc"
                       ? request.sort.ToLower() switch
                       {
                           "id" => query.OrderByDescending(e => e.Id),
                           "firstname" => query.OrderByDescending(e => e.FirstName),
                           "lastname" => query.OrderByDescending(e => e.LastName),
                           "position" => query.OrderByDescending(e => e.Position),
                           "email" => query.OrderByDescending(e => e.Email),
                           "phonenumber" => query.OrderByDescending(e => e.PhoneNumber),
                           "company" => query.OrderByDescending(e => e.Company.Name),
                           _ => query.OrderByDescending(e => EF.Property<object>(e, request.sort))
                       }
                       : request.sort.ToLower() switch
                       {
                           "id" => query.OrderBy(e => e.Id),
                           "firstname" => query.OrderBy(e => e.FirstName),
                           "lastname" => query.OrderBy(e => e.LastName),
                           "position" => query.OrderBy(e => e.Position),
                           "email" => query.OrderBy(e => e.Email),
                           "phonenumber" => query.OrderBy(e => e.PhoneNumber),
                           "company" => query.OrderBy(e => e.Company.Name),
                           _ => query.OrderBy(e => EF.Property<object>(e, request.sort))
                       };
                }
                else
                {
                    query = query.OrderByDescending(e => e.Id);
                }

                // Aplicar paginación y seleccionar resultados
                var total = query.Count();
                var employees = query.Skip(request.offset)
                                 .Take(request.limit)
                                 .ToList()
                                 .Select(e => new EmployeeReadDto
                                 {
                                     Id = e.Id,
                                     FirstName = e.FirstName,
                                     LastName = e.LastName,
                                     Position = e.Position,
                                     Email = e.Email,
                                     PhoneNumber = e.PhoneNumber,
                                     Company = e.Company?.Name ?? "Sin empresa",
                                     CompanyId = e.CompanyId
                                 })
                                 .ToList();

                return Json(new { total, rows = employees });
            }
            catch (FormatException e)
            {
                return Json(e.Message);
            }
            catch (NpgsqlException e)
            {
                return Json(e.Message);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public async Task<IActionResult> GetList()
        {
            try
            {
                var employees = await _context.Employees
                    .OrderBy(e => e.FirstName)
                    .ThenBy(e => e.LastName)
                    .Select(e => new { label = $"{e.FirstName} {e.LastName}", value = e.Id , description = e.Position})
                    .ToListAsync();

                return Json(employees);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

ChronosSuite/Controllers/LocationController.cs
using ChronosSuite.Models;
using ChronosSuite.Models.Dto.Location;
using DannteV2.Models.Dto.FiltersTable;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Text.Json;

namespace ChronosSuite.Controllers
{
    [Authorize]
    public class LocationController : Controller
    {
        private readonly PgDbContext _context;

        public LocationController(PgDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Location = "active";
            return View();
        }

        [HttpPost]
        public IActionResult GetAll([FromBody] TableRequest<FilterLocation>? request)
        {
            try
            {
                if (request == null || request.filter == null)
                    return Json(new { success = false, message = "Solicitud inválida." });

                var query = _context.Locations.AsQueryable();

                // Aplicar filtros si están presentes
                if (!string.IsNullOrEmpty(request.filter.Id))
                {
                    if (long.TryParse(request.filter.Id, out long locationId))
                    {
                        query = query.Where(l => l.Id == locationId);
                    }
                }

                if (!string.IsNullOrEmpty(request.filter.Name))
                    query = query.Where(l => l.Name.Contains(request.filter.Name));

                if (!string.IsNullOrEmpty(request.filter.Description))
                    query = query.Where(l => l.Description != null && l.Description.Contains(request.filter.Description));

                // Aplicar ordenamiento
                if (!string.IsNullOrEmpty(request.sort))
                {
                    query = request.order == "desc"
                       ? request.sort.ToLower() switch
                       {
                           "id" => query.OrderByDescending(l => l.Id),
                           "name" => query.OrderByDescending(l => l.Name),
                           "description" => query.OrderByDescending(l => l.Description),
                           _ => query.OrderByDescending(l => EF.Property<object>(l, request.sort))
                       }
                       : request.sort.ToLower() switch
                       {
                           "id" => query.OrderBy(l => l.Id),
                           "name" => query.OrderBy(l => l.Name),
                           "description" => query.OrderBy(l => l.Description),
                           _ => query.OrderBy(l => EF.Property<object>(l, request.sort))
                       };
                }
                else
                {
                    query = query.OrderByDescending(l => l.Id);
                }

                // Aplicar paginación y seleccionar resultados
                var total = query.Count();
                var locations = query.Skip(request.offset)
                                 .Take(request.limit)
                                 .ToList()
                                 .Select(l => new LocationReadDto
                                 {
                                     Id = l.Id,
                                     Name = l.Name,
                                     Description = l.Description
                                 })
                                 .ToList();

                return Json(new { total, rows = locations });
            }
            catch (FormatException e)
            {
                return Json(e.Message);
            }
            catch (NpgsqlException e)
            {
                return Json(e.Message);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public async Task<IActionResult> GetList()
        {
            try
            {
                var role = await _context.Locations
                                            .AsNoTracking()
                                            .Select(p => new
                                            {
                                                value = p.Id,
                                                label = p.Name
                                            })
                                            .ToListAsync();
                return Json(role);
            }
            catch (FormatException e)
            {
                return Json(e.Message);
            }
            catch (NpgsqlException e)
            {
                return Json(e.Message);

            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
    }
}

ChronosSuite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChronosSuite</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-table/bootstrap-table.css" rel="stylesheet" />
    <link href="~/css/virtual-select.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <div class="sidebar gradient-1-90">
            <div class="text-center p-2">
                <!-- Logo -->
                <img src="~/images/Chronos-negativo.svg" class="img-fluid" alt="" />
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a class="sidebar-link text-light @ViewBag.Home" asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house-door"></i>
                        <span>Inicio</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link text-light @ViewBag.VisitRecord" asp-controller="VisitRecord" asp-action="Index">
                        <i class="bi bi-clipboard-check"></i>
                        <span>Registros</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link text-light @ViewBag.Visitor" asp-controller="Visitor" asp-action="Index">
                        <i class="bi bi-person-badge"></i>
                        <span>Visitantes</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link text-light @ViewBag.Employee" asp-controller="Employee" asp-action="Index">
                        <i class="bi bi-people"></i>
                        <span>Empleados</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link text-light @ViewBag.Location" asp-controller="Location" asp-action="Index">
                        <i class="bi bi-geo-alt"></i>
                        <span>Ubicaciones</span>
                    </a>
                </li>
            </ul>
        </div>

        <div class="main">
            <nav class="navbar navbar-expand-lg shadow-lg">
                <div class="container-fluid">
                    <div class="toggle-btn" type="button" id="sidebarToggle">
                        <i class="bi bi-list fs-4"></i>
                    </div>

                    <div class="d-flex ms-auto">
                        <div class="dropdown">
                            <a class="btn dropdown-toggle d-flex align-items-center" href="#" role="button"
                                id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class="me-2 d-none d-md-inline">@(User.Identity?.Name ?? "Usuario")</span>
                                <i class="bi bi-person-circle fs-4"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li><a class="dropdown-item" href="/Login/SignOut" id="logout-link"><i
                                            class="bi bi-box-arrow-right me-2"></i>Cerrar Sesión</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>

            <div class="container-fluid p-3">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   
    <script src="https://cdn.jsdelivr.net/npm/tableexport.jquery.plugin@1.29.0/tableExport.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/bootstrap-table.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/bootstrap-table-locale-all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/extensions/export/bootstrap-table-export.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-table@1.24.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.24.0/extensions/auto-refresh/bootstrap-table-auto-refresh.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/virtual-select-plugin@1.0.49/dist/virtual-select.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>